# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX enables standard, clean libraries to replace Support Libraries.
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX.
android.enableJetifier=true

# R8 / ProGuard Full Mode and Resource Optimization
android.enableR8.fullMode=true
android.r8.strictFullModeForKeepRules=true
android.r8.optimizedResourceShrinking=true

# Kotlin code-style
kotlin.code.style=official
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.builtInKotlin=false
android.newDsl=false
