pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "SSP"

include ':core:common'
include ':core:data'
include ':core:ui'
include ':core:hardware'
include ':core:payment'

include ':feature:retail'
include ':feature:apex'
include ':feature:wash'
include ':feature:vending'
include ':feature:parking'
include ':feature:ev'

include ':libs:pax'
include ':libs:wizarpos'

include ':app:iris'
include ':app:ourea'
include ':app:aegis-wash'
include ':app:aegis-vend'
include ':app:aegis-ev'
